# Windows customizations
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 10
    y: 10
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 0.9

# Font configuration
font:
  normal:
    family: Fira Code Monaco Droid Sans Mono Slashed for Powerline
    style: Regular
  bold:
    family: Fira Code Monaco Droid Sans Mono Slashed for Powerline
    style: Bold
  italic:
    family: Fira Code Monaco Droid Sans Mono Slashed for Powerline
    style: Italic
  size: 16.0

# Colors (Night Owl by Sarah Drasner)
colors:
  # Default colors
  primary:
    background: '0x011627'
    foreground: '0xd6deeb'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x7e57c2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xef5350'
    green:   '0x22da6e'
    yellow:  '0xaddb67'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x21c7a8'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x575656'
    red:     '0xef5350'
    green:   '0x22da6e'
    yellow:  '0xffeb95'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x7fdbca'
    white:   '0xffffff'

  cursor:
    style: Block
    unfocused_hollow: true
# Keybindings
key_bindings:
  - { key: N,      mods: Control|Shift,       action: SpawnNewInstance            }
